import { Feather } from '@expo/vector-icons';
import { Platform, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

export default function AudioScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  return <View style={[styles.screen, { backgroundColor: colors.background, paddingTop: insets.top + (Platform.OS === 'web' ? 67 : 18), paddingBottom: insets.bottom + 90 }]}>
    <Text style={[styles.eyebrow, { color: colors.primary }]}>ON-DEVICE AUDIO</Text><Text style={[styles.title, { color: colors.foreground }]}>Voice, without the cloud.</Text>
    <View style={[styles.hero, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.icon, { backgroundColor: colors.accent }]}><Feather name="activity" size={28} color={colors.primary} /></View><Text style={[styles.cardTitle, { color: colors.cardForeground }]}>Native build required</Text><Text style={[styles.body, { color: colors.mutedForeground }]}>Chatterbox and Voice Follow need native iPhone audio and inference modules. Expo Go cannot load those modules, so this preview does not pretend to generate or recognise speech.</Text></View>
    <View style={styles.steps}>{['Codex assessed the complete desktop pipeline', 'A physical iPhone experiment is still required', 'Your scripts and recordings will remain local'].map((text, index) => <View key={text} style={styles.step}><View style={[styles.number, { borderColor: colors.primary }]}><Text style={[styles.numberText, { color: colors.primary }]}>{index + 1}</Text></View><Text style={[styles.stepText, { color: colors.foreground }]}>{text}</Text></View>)}</View>
    <Text style={[styles.note, { color: colors.mutedForeground }]}>No audio is recorded, uploaded, or generated by this Expo Go build.</Text>
  </View>;
}
const styles = StyleSheet.create({
  screen: { flex: 1, paddingHorizontal: 20 },
  eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 2.4, marginBottom: 9 },
  title: { fontFamily: 'Inter_700Bold', fontSize: 34, lineHeight: 39, letterSpacing: -1.2, maxWidth: 330 },
  hero: { marginTop: 28, padding: 22, borderWidth: 1, borderRadius: 20 },
  icon: { width: 56, height: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginBottom: 24 },
  cardTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 20, marginBottom: 10 },
  body: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 23 },
  steps: { gap: 18, marginTop: 28 },
  step: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  number: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  numberText: { fontFamily: 'Inter_700Bold', fontSize: 12 },
  stepText: { flex: 1, fontFamily: 'Inter_500Medium', fontSize: 14, lineHeight: 20 },
  note: { fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginTop: 'auto' },
});